### ISSUE TITLE
Create new project with PlayFrameWork

### ISSUE THREAD

**Issue by hieunguyenvanLC** [PlayFrameWorkTraining/PlayFrameWork-Training#1]
Use cook book to create new project with PlayFrameWork.
Know how to use List to save simple information and show in scala.html.
Submit all code.
Link Cook Book pdf:

[reactive_apps.pdf](https://github.com/PlayFrameWorkTraining/PlayFrameWork-Training/files/1210752/reactive_apps.pdf)

Due by by August 11, 2017.

**Comment by anh-khue** [comment]
![capture](https://user-images.githubusercontent.com/28884098/29131953-bc24e78c-7d58-11e7-94ed-9f768e8d34b3.PNG)
@hieunguyenvanLC Please check this error, I do not have the permission to push anything to the repository. Thanks in advance.

**Comment by hieunguyenvanLC** [comment]
Sorry about that. I just accept you to push in this Repo. Please try againt @khuetla.

**Comment by anh-khue** [comment]
@hieunguyenvanLC  I still cannot push in this repository. 
I've even tried to clear everything and clone this repository again but it still did not work. I've kept getting that error.
